yml4

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,14 +18,14 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 16
-          cache: "npm" # Enable npm cache
+          cache: "yarn" # Enable npm cache
 
       - name: Install dependencies
-        run: npm ci # Using npm ci instead of npm install for cleaner installs
+        run: yarn ci # Using npm ci instead of npm install for cleaner installs
 
       - name: Build project
         run: |
-          npm run build || (echo "Build failed" && exit 1)
+          yarn build || (echo "Build failed" && exit 1)
 
       - name: Upload production-ready build files
         uses: actions/upload-artifact@v4
